@startuml
left to right direction

package "Usuario y Atuendos" {
    class User {
        -items: Garment[*]
        +uploadItem(item: Garment): void
    }

    class Outfit {
        +items: Garment[*]
    }

    User --> Garment : owns
    User --> Outfit : wears
    Outfit --> Garment : contains
}

package "Prendas" {
    class Garment {
        +category: Category
        +mainColor: String
        +secondaryColor: String
        +isValidColor(String colorName)
    }

    class GarmentDraft {
    }

    class TypeOfGarment {
        +name: String
    }

    enum Category {
        ParteSuperior
        ParteInferior
        Calzado
        Accessory
    }

    Garment --> TypeOfGarment : has
    Garment --> Material : has
    GarmentDraft --> Material
    GarmentDraft --> TypeOfGarment
    TypeOfGarment --> Category : belongs
}

package "Materiales" {
    class Material {
        +trama: weft
        +material: Material
        +mainColor: Color
        +secondaryColor: Color
    }

    class Color {
        +isInvalidColor(color string)
    }

    enum Weft {
        lisa
        rayada
        lunares
        cuadros
        estampado
    }

    enum TypeMaterial {
        ALGODON
        LANA
        TELA
        PIQUE
        ACETATO
        CUERO
    }

    Material --> TypeMaterial
    Material --> Weft
    Material --> Color
}

@enduml

